### ISSUE TITLE
I got errors while building this project

### ISSUE THREAD

**Issue by JoestarK** [robofit/but_velodyne#17]
CMakeFiles/coloring.dir/src/coloring-node.cpp.o: In function `cv::String::String(char const*)':
/usr/local/include/opencv2/core/cvstd.hpp:618: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/coloring.dir/src/coloring-node.cpp.o: In function `cv::String::~String()':
/usr/local/include/opencv2/core/cvstd.hpp:660: undefined reference to `cv::String::deallocate()'
CMakeFiles/coloring.dir/src/coloring-node.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
/usr/local/include/opencv2/core/mat.inl.hpp:413: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/coloring.dir/src/Image.cpp.o: In function `but_calibration_camera_velodyne::Image::Image::computeIDTEdgeImage(cv::Mat&)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Image.cpp:123: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
CMakeFiles/coloring.dir/src/Velodyne.cpp.o: In function `but_calibration_camera_velodyne::Velodyne::Velodyne::project(cv::Mat, cv::Rect_<int>, pcl::PointCloud<but_calibration_camera_velodyne::Velodyne::Point>*)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Velodyne.cpp:75: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
CMakeFiles/coloring.dir/src/Velodyne.cpp.o: In function `but_calibration_camera_velodyne::Velodyne::Velodyne::depthSegmentation(int)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Velodyne.cpp:225: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/zzwu/but_velo/devel/lib/but_calibration_camera_velodyne/coloring] Error 1
make[1]: *** [but_velodyne/but_calibration_camera_velodyne/CMakeFiles/coloring.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libpcl_common.so, may conflict with libboost_system.so.1.58.0
/usr/bin/ld: warning: libboost_thread.so.1.54.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libpcl_common.so, may conflict with libboost_thread.so.1.58.0
/usr/bin/ld: warning: libboost_filesystem.so.1.54.0, needed by /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libpcl_io.so, may conflict with libboost_filesystem.so.1.58.0
/usr/bin/ld: warning: libboost_regex.so.1.54.0, needed by /opt/ros/indigo/lib/libcv_bridge.so, may conflict with libboost_regex.so.1.58.0
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `operator<<':
/usr/local/include/opencv2/core/persistence.hpp:1076: undefined reference to `cv::operator<<(cv::FileStorage&, cv::String const&)'
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `writeAllInputs()':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/calibration-node.cpp:58: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/calibration-node.cpp:59: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `operator<< <cv::Mat>':
/usr/local/include/opencv2/core/persistence.hpp:1064: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
/usr/local/include/opencv2/core/persistence.hpp:1065: undefined reference to `cv::write(cv::FileStorage&, cv::String const&, cv::Mat const&)'
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `cv::String::String(char const*)':
/usr/local/include/opencv2/core/cvstd.hpp:618: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `cv::String::~String()':
/usr/local/include/opencv2/core/cvstd.hpp:660: undefined reference to `cv::String::deallocate()'
CMakeFiles/calibration.dir/src/calibration-node.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
/usr/local/include/opencv2/core/mat.inl.hpp:413: undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/calibration.dir/src/Image.cpp.o: In function `but_calibration_camera_velodyne::Image::Image::computeIDTEdgeImage(cv::Mat&)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Image.cpp:123: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
CMakeFiles/calibration.dir/src/Velodyne.cpp.o: In function `but_calibration_camera_velodyne::Velodyne::Velodyne::project(cv::Mat, cv::Rect_<int>, pcl::PointCloud<but_calibration_camera_velodyne::Velodyne::Point>*)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Velodyne.cpp:75: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
CMakeFiles/calibration.dir/src/Velodyne.cpp.o: In function `but_calibration_camera_velodyne::Velodyne::Velodyne::depthSegmentation(int)':
/home/zzwu/but_velo/src/but_velodyne/but_calibration_camera_velodyne/src/Velodyne.cpp:225: undefined reference to `cv::normalize(cv::_InputArray const&, cv::_InputOutputArray const&, double, double, int, int, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/zzwu/but_velo/devel/lib/but_calibration_camera_velodyne/calibration] Error 1
make[1]: *** [but_velodyne/but_calibration_camera_velodyne/CMakeFiles/calibration.dir/all] Error 2
[ 59%] Linking CXX shared library /home/zzwu/but_velo/devel/lib/libbutvelo_laserscan_nodelet.so
[ 62%] Linking CXX shared library /home/zzwu/but_velo/devel/lib/libbutvelo_groundmap_nodelet.so
[ 65%] Linking CXX executable /home/zzwu/but_velo/devel/lib/but_velodyne_proc/laser_scan
[ 65%] Built target butvelo_laserscan_nodelet
[ 68%] Linking CXX executable /home/zzwu/but_velo/devel/lib/but_velodyne_proc/ground_map
[ 68%] Built target butvelo_groundmap_nodelet
[ 68%] Built target laser_scan
[ 68%] Built target ground_map
[ 71%] Linking CXX shared library /home/zzwu/but_velo/devel/lib/libbutvelo_cloudassembler_nodelet.so
[ 71%] Built target butvelo_cloudassembler_nodelet
[ 75%] Linking CXX executable /home/zzwu/but_velo/devel/lib/but_velodyne_proc/cloud_assembler
[ 75%] Built target cloud_assembler
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by JoestarK** [comment]
opencv version 3.0.0
ubuntu 14.04LTS

**Comment by martin-velas** [comment]
Hi! These packages were made using OpenCV version 2.4.9 and I do not expect compatibility with v3. Try 2.4.9 please.

**Comment by JoestarK** [comment]
@martin-velas 
Thanks! I just built but_velodyne_odom and but_velodyne_proc , ignored the first one. That works....
